/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppCalendar {
        "color": string;
        "name": string;
    }
    interface AppFirstcomponent {
        "name": string;
    }
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppCalendarElement extends Components.AppCalendar, HTMLStencilElement {
    }
    var HTMLAppCalendarElement: {
        prototype: HTMLAppCalendarElement;
        new (): HTMLAppCalendarElement;
    };
    interface HTMLAppFirstcomponentElement extends Components.AppFirstcomponent, HTMLStencilElement {
    }
    var HTMLAppFirstcomponentElement: {
        prototype: HTMLAppFirstcomponentElement;
        new (): HTMLAppFirstcomponentElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-calendar": HTMLAppCalendarElement;
        "app-firstcomponent": HTMLAppFirstcomponentElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppCalendar {
        "color"?: string;
        "name"?: string;
    }
    interface AppFirstcomponent {
        "name"?: string;
    }
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-calendar": AppCalendar;
        "app-firstcomponent": AppFirstcomponent;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-calendar": LocalJSX.AppCalendar & JSXBase.HTMLAttributes<HTMLAppCalendarElement>;
            "app-firstcomponent": LocalJSX.AppFirstcomponent & JSXBase.HTMLAttributes<HTMLAppFirstcomponentElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
