/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppCalendar {
    }
    interface AppDay {
        "date": Date;
    }
    interface AppHome {
    }
    interface AppMonth {
        "date": Date;
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppRoute {
    }
    interface AppWeek {
        "date": Date;
    }
}
declare global {
    interface HTMLAppCalendarElement extends Components.AppCalendar, HTMLStencilElement {
    }
    var HTMLAppCalendarElement: {
        prototype: HTMLAppCalendarElement;
        new (): HTMLAppCalendarElement;
    };
    interface HTMLAppDayElement extends Components.AppDay, HTMLStencilElement {
    }
    var HTMLAppDayElement: {
        prototype: HTMLAppDayElement;
        new (): HTMLAppDayElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMonthElement extends Components.AppMonth, HTMLStencilElement {
    }
    var HTMLAppMonthElement: {
        prototype: HTMLAppMonthElement;
        new (): HTMLAppMonthElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppRouteElement extends Components.AppRoute, HTMLStencilElement {
    }
    var HTMLAppRouteElement: {
        prototype: HTMLAppRouteElement;
        new (): HTMLAppRouteElement;
    };
    interface HTMLAppWeekElement extends Components.AppWeek, HTMLStencilElement {
    }
    var HTMLAppWeekElement: {
        prototype: HTMLAppWeekElement;
        new (): HTMLAppWeekElement;
    };
    interface HTMLElementTagNameMap {
        "app-calendar": HTMLAppCalendarElement;
        "app-day": HTMLAppDayElement;
        "app-home": HTMLAppHomeElement;
        "app-month": HTMLAppMonthElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-route": HTMLAppRouteElement;
        "app-week": HTMLAppWeekElement;
    }
}
declare namespace LocalJSX {
    interface AppCalendar {
    }
    interface AppDay {
        "date"?: Date;
    }
    interface AppHome {
    }
    interface AppMonth {
        "date"?: Date;
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppRoute {
    }
    interface AppWeek {
        "date"?: Date;
    }
    interface IntrinsicElements {
        "app-calendar": AppCalendar;
        "app-day": AppDay;
        "app-home": AppHome;
        "app-month": AppMonth;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-route": AppRoute;
        "app-week": AppWeek;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-calendar": LocalJSX.AppCalendar & JSXBase.HTMLAttributes<HTMLAppCalendarElement>;
            "app-day": LocalJSX.AppDay & JSXBase.HTMLAttributes<HTMLAppDayElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-month": LocalJSX.AppMonth & JSXBase.HTMLAttributes<HTMLAppMonthElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-route": LocalJSX.AppRoute & JSXBase.HTMLAttributes<HTMLAppRouteElement>;
            "app-week": LocalJSX.AppWeek & JSXBase.HTMLAttributes<HTMLAppWeekElement>;
        }
    }
}
